### ISSUE TITLE
Feature Request: Option to switch the order of Yellow/Double Yellow Signal

### ISSUE THREAD

**Issue by innocenat** [JGRennison/multi-aspect-signals-grf#1]
Not sure if you accept feature request to this GRF, but here goes.

Yes, it's weird, and I don't understand why, but in Japan, the aspect goes like this: G -> (GY) -> Y -> (YY) -> R (the aspect in parentheses doesn't always exist), unlike in UK and this GRF.

If it's not too hard, I would like an option to switch the display aspect to G -> Y -> YY -> R (basically switch YY and Y), as I am very used to the Japanese way and it is just weird seeing the signal aspect in different order than I am accustomed to.

**Comment by JGRennison** [comment]
This is no problem, it's added and should be in the most recent version on bananas.

**Comment by innocenat** [comment]
Thanks for such a quick update!
